name: "Pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Build Jar file"
        run: mvn clean package
      - name: "Get commit SHA"
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: "Release Jar file"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "prerelease"
          prerelease: true
          title: "Commit ${{ env.GITHUB_SHA_SHORT }}"
          files: "target/*-All.jar"
