name: "Pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Download lavaplayer-natives-extra from GitHub
        run: |
          mkdir -p ~/.m2/repository/com/sedmelluq/lavaplayer-natives-extra/1.3.13
          wget "https://github.com/sedmelluq/lavaplayer/files/6563671/lavaplayer-natives-extra-1.3.13.zip" -O ~/.m2/repository/com/sedmelluq/lavaplayer-natives-extra/1.3.13/tmp.zip
          unzip -o ~/.m2/repository/com/sedmelluq/lavaplayer-natives-extra/1.3.13/tmp.zip -d ~/.m2/repository/com/sedmelluq/lavaplayer-natives-extra/1.3.13/
          rm ~/.m2/repository/com/sedmelluq/lavaplayer-natives-extra/1.3.13/tmp.zip
      - name: Build Jar file
        run: mvn clean package
      - name: Get commit SHA
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Release Jar file
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Commit ${{ env.GITHUB_SHA_SHORT }}"
          files: "target/*-All.jar"

  pre-release-docker:
    name: Prerelease docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker 
